
# Note: this project has 3 source files
# From now on I put all calculators into separate cpp files

cc_binary(
    name="1_3",
    srcs=["main.cpp", "string_source_calculator.cpp", "string_join_calculator.cpp"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:parse_text_proto",
    ],
)
