cc_binary(
    name="3_2",
    srcs=["main.cpp", "slow_calculator.cpp"],
    deps=[
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/calculators/core:flow_limiter_calculator",
        "//mediapipe/framework/formats:image_frame",
        "//mediapipe/framework/formats:image_frame_opencv",
        "//mediapipe/framework/port:opencv_highgui",
        "//mediapipe/framework/port:opencv_imgproc",
        "//mediapipe/framework/port:parse_text_proto",
        "//mediapipe/framework/port:status",
    ],
)
