cc_binary(
    name="1_5",
    srcs=["main.cpp", "goblin_calculator15.cpp"],
    deps = [
        "//mediapipe/framework:calculator_framework",
        "//mediapipe/framework/port:parse_text_proto",
    ],
)
